<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>嵌套的错误处理</title>
  </head>
  <body>

    <script type="text/javascript">

    try{
      try{
        var err = new Error("oops");
        // 抛出一个错误
        throw err;
      }
      catch(e){
        console.log("inner error = ", e.message);
        /*
         错误是可以向外传递的，如果内部没有错误捕获语句，
         那么错误会继续向外传输，直到有catch 捕获语句
        */
      }
      finally{
        console.log("in inner  finally ...");
      }
    }
    catch(ex){
        console.log("outer error = ", ex.message);
    }
    finally {
      console.log("in outer finally ...");
    }

    console.log("after outer finally ...");
    </script>

  </body>
</html>
